### ISSUE TITLE
pifi status crashes the program as does add or remove. Only changing hostname seems to work

### ISSUE THREAD

**Issue by CS-RGRobotix** [rohbotics/pifi#36]
I've tried installing, uninstalling. Nada. I'm on ros melodic on a raspi 4

My output from terminal
```
pi@llt0001:~/pifi $ pifi status
Traceback (most recent call last):
File "/usr/local/bin/pifi", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.7/dist-packages/pifi/pifi.py", line 347, in main
commands[args.command](argv[1:])
File "/usr/local/lib/python3.7/dist-packages/pifi/pifi.py", line 69, in status
for ApModeDevice in nm.managedAPCapableDevices():
File "/usr/local/lib/python3.7/dist-packages/pifi/nm_helper.py", line 96, in managedAPCapableDevices
for device in managedWifiDevices(NetworkManager=NetworkManager):
File "/usr/local/lib/python3.7/dist-packages/pifi/nm_helper.py", line 85, in managedWifiDevices
for device in NetworkManager.NetworkManager.GetDevices():
File "<string>", line 3, in GetDevices
 File "/home/pi/.local/lib/python3.7/site-packages/NetworkManager.py", line 261, in proxy
self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path, follow_name_owner_changes=True)File "/home/pi/.local/lib/python3.7/site-packages/dbus/bus.py", line 225, in get_object
self._require_main_loop()   # we don't get the signals otherwise
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)     
```

**Comment by alberto1995** [comment]
I have the same problem
